{% set name = "musdb" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6db4d5e4bf26c9982a9387ac617fae7fc8182c0485fc49b443727123de8be053

build:
  number: 0
  noarch: python
  # skip: true  # [win or py<36 or py38]
  entry_points:
    - musdbconvert=musdb.tools:musdb_convert
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.7
    - pyaml
    - pysoundfile >=0.9.0
    - stempeg >=0.1.7
    - tqdm
    - ffmpeg
    - setuptools

test:
  imports:
    - musdb
  commands:
    - pip check
    - musdbconvert --help
  requires:
    - pip

about:
  home: https://github.com/sigsep/sigsep-mus-db
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python parser and tools for MUSDB18 Music Separation Dataset
  doc_url: https://sigsep.github.io/sigsep-mus-db
  dev_url: https://github.com/sigsep/sigsep-mus-db

extra:
  recipe-maintainers:
    - Faylixe
